---

- name: Install the prerequisites
  ansible.builtin.apt:
    update_cache: yes 
    pkg: 
      - curl      
      - gnupg2
      - ca-certificates
      - lsb-release
      - ubuntu-keyring
      - htop
    state: present

- name : add nginx apt key
  ansible.builtin.apt_key:    
    url: https://nginx.org/keys/nginx_signing.key
    keyring: "{{ nginx_default_keyring_path }}"
    id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    state: present

- name : add stable ngix packages apt repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by={{ nginx_default_keyring_path }}] http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx
    state: present
    #update_cache: yes 

- name: install nginx 
  ansible.builtin.apt:  
    name: nginx
    state: present
    #update_cache: yes 

- name: Start service nginx, if not started
  ansible.builtin.service:
    name: nginx
    state: started
